### ISSUE TITLE
Validation concat method

### ISSUE THREAD

**Issue by JesterXL** [expede/witchcraft#50]
Hey, I'm trying to create a [validator like Folktale](http://folktale.origamitower.com/api/v2.0.0/en/folktale.validation.html). However, my spec for concat doesn't compile; I feel like I'm uber close:

```elixir
defmodule Validator.Success do

    alias Validator.Success

    defdata any()

    @spec new(any()) :: t()
    def new(inner), do: %Success{success: inner}    
end

defmodule Validator.Failure do

    alias Validator.Failure

    defdata list()

    @spec new(any()) :: t()
    def new(inner), do: %Failure{failure: inner}    

    @spec concat(Witchcraft.Semigroup.t) :: [Witchcraft.Semigroup.t]
    def concat(a, b), do: a.failure <> b.failure
end
```

```shell
== Compilation error in file lib/aws/validators.ex ==
** (CompileError) lib/aws/validators.ex:36: spec for undefined function concat/1
    (stdlib) lists.erl:1338: :lists.foreach/2
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

If I remove the spec concat stuff, it compiles and my unit tests work, so... hopefully it's something small?

**Comment by OvermindDL1** [comment]
> ```elixir
    @spec concat(Witchcraft.Semigroup.t) :: [Witchcraft.Semigroup.t]
    def concat(a, b), do: a.failure <> b.failure
```

Your spec defines `concat/1`, yet you implement `concat/2`.  :-)
This is an elixir thing, not a witchcraft thing.  :-)

**Comment by JesterXL** [comment]
WHOOPS!! Nice catch, doh, lemme try...

**Comment by JesterXL** [comment]
POW! Ok, it compiles now. Doesn't work, but compiles, so huge step!

```elixir
@spec concat(Witchcraft.Semigroup.t, Witchcraft.Semigroup.t) :: [Witchcraft.Semigroup.t]
    def concat(a, b), do: a.failure <> b.failure
```

```elixir
test "Adding 2 failures" do
    failure1 = Validator.Failure.new(["boom 1"])
    failure2 = Validator.Failure.new(["another boom 2"])
    result = Validator.Failure.concat(failure1, failure2)
    Logger.debug inspect(List.first(result))
  end
```

Prints out "boom 1", heh, so she ain't concating. I'll figure it out, thanks a ton for the help again!!!

**Comment by JesterXL** [comment]
Doh, `List.first`, I'm a moron, NOW WE'RE PLAYING' WIF POWAH! I love these libraries, y'all.
